name: Deploy Backend to Render

on:
  push:
    branches: [ main ] # Or your default branch
    # Optional: Trigger only if backend files change
    # paths:
    #   - 'fms_backend/**'
    #   - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Note: Building/testing the Docker image here is optional but recommended
      # If you build here, you might push to a registry (like Docker Hub or GHCR)
      # and have Render pull the pre-built image, which can be faster.
      # The current setup assumes Render builds the image from the Dockerfile.

      - name: Trigger Render Deploy Hook
        # Use Render's deploy hook URL for simplicity if you don't need complex build steps here
        # Find the Deploy Hook URL in your Render service settings
        # Store the hook URL as a secret in GitHub: RENDER_BACKEND_DEPLOY_HOOK_URL
        run: curl -X POST ${{ secrets.RENDER_BACKEND_DEPLOY_HOOK_URL }}
        # If the hook URL is not available or you prefer API key method:
        # - name: Install Render CLI (if needed)
        #   run: | # Example, adjust based on Render CLI installation
        #     npm install -g @renderinc/render-cli 
        # - name: Trigger Render Deploy via API
        #   env:
        #     RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        #     RENDER_BACKEND_SERVICE_ID: ${{ secrets.RENDER_BACKEND_SERVICE_ID }} # Get from Render service settings
        #   run: render deploy --service-id $RENDER_BACKEND_SERVICE_ID

